import "./globals.css";
// import SessionProviderWrapper from "@/utils/SessionWrapper";

// Define metadata for the page (server-side)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// This part remains a server component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* <SessionProviderWrapper> */}
          {children}
        {/* </SessionProviderWrapper> */}
      </body>
    </html>
  );
}
